// Mock data for dev/demo mode
import { Player, Group, Session, AttendanceRecord, SkillAssessment, ProgressReport, Drill, PracticePlan, Announcement, PlayerBadge, PaymentRecord, SKILL_DEFINITIONS, BADGE_DEFINITIONS, DashboardStats } from "./types";

export { SKILL_DEFINITIONS, BADGE_DEFINITIONS, STAGE_INFO } from "./types";

export const DEMO_PLAYERS: Player[] = [
  {
    id: "player-1",
    first_name: "Emma",
    last_name: "Johnson",
    preferred_name: "Emma",
    date_of_birth: "2016-03-15",
    age: 9,
    skill_stage: "orange",
    experience_level: "beginner",
    dominant_hand: "right",
    guardians: [
      { id: "g-1", full_name: "Lisa Johnson", email: "lisa@example.com", phone: "555-0101", relationship: "mother", is_primary: true, is_emergency_contact: true },
    ],
    emergency_contact: { id: "g-2", full_name: "Mark Johnson", email: "mark@example.com", phone: "555-0102", relationship: "father", is_primary: false, is_emergency_contact: true },
    medical_notes: "No known allergies. Mild asthma, inhaler in bag.",
    allergies: "None",
    photo_consent: true,
    video_consent: true,
    participation_consent: true,
    coach_notes: "Very enthusiastic, listens well, needs work on backhand.",
    status: "active",
    group_id: "group-orange-1",
    shirt_size: "Youth M",
    equipment: { racket: true, shoes: true, water_bottle: true },
    created_at: "2024-09-01T00:00:00Z",
    updated_at: "2025-05-15T00:00:00Z",
  },
  {
    id: "player-2",
    first_name: "Lucas",
    last_name: "Martinez",
    preferred_name: "Lucas",
    date_of_birth: "2015-07-22",
    age: 10,
    skill_stage: "green",
    experience_level: "developing",
    dominant_hand: "left",
    guardians: [
      { id: "g-3", full_name: "Ana Martinez", email: "ana@example.com", phone: "555-0103", relationship: "mother", is_primary: true, is_emergency_contact: true },
    ],
    emergency_contact: { id: "g-3", full_name: "Ana Martinez", email: "ana@example.com", phone: "555-0103", relationship: "mother", is_primary: true, is_emergency_contact: true },
    medical_notes: "",
    allergies: "Peanuts",
    photo_consent: true,
    video_consent: false,
    participation_consent: true,
    coach_notes: "Strong forehand, good footwork. Left-handed advantage.",
    status: "active",
    group_id: "group-green-1",
    shirt_size: "Youth L",
    equipment: { racket: true, shoes: false, water_bottle: true },
    created_at: "2024-08-15T00:00:00Z",
    updated_at: "2025-05-10T00:00:00Z",
  },
  {
    id: "player-3",
    first_name: "Sophia",
    last_name: "Chen",
    preferred_name: "Sophie",
    date_of_birth: "2017-11-05",
    age: 7,
    skill_stage: "red",
    experience_level: "new_beginner",
    dominant_hand: "right",
    guardians: [
      { id: "g-4", full_name: "David Chen", email: "david@example.com", phone: "555-0104", relationship: "father", is_primary: true, is_emergency_contact: true },
      { id: "g-5", full_name: "Amy Chen", email: "amy@example.com", phone: "555-0105", relationship: "mother", is_primary: false, is_emergency_contact: false },
    ],
    emergency_contact: { id: "g-4", full_name: "David Chen", email: "david@example.com", phone: "555-0104", relationship: "father", is_primary: true, is_emergency_contact: true },
    medical_notes: "",
    allergies: "None",
    photo_consent: true,
    video_consent: true,
    participation_consent: true,
    coach_notes: "Newest player, very shy but eager. Great listener.",
    status: "active",
    group_id: "group-red-1",
    shirt_size: "Youth S",
    equipment: { racket: false, shoes: false, water_bottle: true },
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-05-18T00:00:00Z",
  },
  {
    id: "player-4",
    first_name: "Oliver",
    last_name: "Williams",
    preferred_name: "Ollie",
    date_of_birth: "2014-04-18",
    age: 11,
    skill_stage: "yellow",
    experience_level: "intermediate",
    dominant_hand: "right",
    guardians: [
      { id: "g-6", full_name: "Sarah Williams", email: "sarah@example.com", phone: "555-0106", relationship: "mother", is_primary: true, is_emergency_contact: true },
    ],
    emergency_contact: { id: "g-6", full_name: "Sarah Williams", email: "sarah@example.com", phone: "555-0106", relationship: "mother", is_primary: true, is_emergency_contact: true },
    medical_notes: "Wears glasses during play.",
    allergies: "None",
    photo_consent: true,
    video_consent: true,
    participation_consent: true,
    coach_notes: "Ready for match play. Strong serve development.",
    status: "active",
    group_id: "group-yellow-1",
    shirt_size: "Youth L",
    equipment: { racket: true, shoes: true, water_bottle: true },
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2025-05-12T00:00:00Z",
  },
  {
    id: "player-5",
    first_name: "Ava",
    last_name: "Garcia",
    preferred_name: "Ava",
    date_of_birth: "2015-09-30",
    age: 10,
    skill_stage: "green",
    experience_level: "intermediate",
    dominant_hand: "left",
    guardians: [
      { id: "g-7", full_name: "Carlos Garcia", email: "carlos@example.com", phone: "555-0107", relationship: "father", is_primary: true, is_emergency_contact: true },
    ],
    emergency_contact: { id: "g-7", full_name: "Carlos Garcia", email: "carlos@example.com", phone: "555-0107", relationship: "father", is_primary: true, is_emergency_contact: true },
    medical_notes: "",
    allergies: "None",
    photo_consent: true,
    video_consent: true,
    participation_consent: true,
    coach_notes: "Consistent player, great court awareness. Potential team leader.",
    status: "active",
    group_id: "group-green-1",
    shirt_size: "Youth M",
    equipment: { racket: true, shoes: true, water_bottle: true },
    created_at: "2024-07-20T00:00:00Z",
    updated_at: "2025-05-14T00:00:00Z",
  },
  {
    id: "player-6",
    first_name: "Noah",
    last_name: "Brown",
    preferred_name: "Noah",
    date_of_birth: "2016-12-08",
    age: 8,
    skill_stage: "orange",
    experience_level: "beginner",
    dominant_hand: "right",
    guardians: [
      { id: "g-8", full_name: "Jennifer Brown", email: "jen@example.com", phone: "555-0108", relationship: "mother", is_primary: true, is_emergency_contact: true },
    ],
    emergency_contact: { id: "g-8", full_name: "Jennifer Brown", email: "jen@example.com", phone: "555-0108", relationship: "mother", is_primary: true, is_emergency_contact: true },
    medical_notes: "EpiPen for bee sting allergy in bag.",
    allergies: "Bee stings",
    photo_consent: true,
    video_consent: true,
    participation_consent: true,
    coach_notes: "Very athletic, quick learner. Needs to slow down and focus.",
    status: "active",
    group_id: "group-orange-1",
    shirt_size: "Youth M",
    equipment: { racket: true, shoes: true, water_bottle: true },
    created_at: "2024-10-05T00:00:00Z",
    updated_at: "2025-05-16T00:00:00Z",
  },
  {
    id: "player-7",
    first_name: "Mia",
    last_name: "Davis",
    preferred_name: "Mia",
    date_of_birth: "2017-02-14",
    age: 8,
    skill_stage: "red",
    experience_level: "beginner",
    dominant_hand: "right",
    guardians: [
      { id: "g-9", full_name: "Rachel Davis", email: "rachel@example.com", phone: "555-0109", relationship: "mother", is_primary: true, is_emergency_contact: true },
    ],
    emergency_contact: { id: "g-9", full_name: "Rachel Davis", email: "rachel@example.com", phone: "555-0109", relationship: "mother", is_primary: true, is_emergency_contact: true },
    medical_notes: "",
    allergies: "None",
    photo_consent: false,
    video_consent: false,
    participation_consent: true,
    coach_notes: "Struggles with confidence but improving. Parent very supportive.",
    status: "active",
    group_id: "group-red-1",
    shirt_size: "Youth S",
    equipment: { racket: false, shoes: false, water_bottle: true },
    created_at: "2025-01-20T00:00:00Z",
    updated_at: "2025-05-17T00:00:00Z",
  },
  {
    id: "player-8",
    first_name: "James",
    last_name: "Wilson",
    preferred_name: "Jamie",
    date_of_birth: "2014-08-03",
    age: 10,
    skill_stage: "yellow",
    experience_level: "advanced_youth",
    dominant_hand: "right",
    guardians: [
      { id: "g-10", full_name: "Tom Wilson", email: "tom@example.com", phone: "555-0110", relationship: "father", is_primary: true, is_emergency_contact: true },
    ],
    emergency_contact: { id: "g-10", full_name: "Tom Wilson", email: "tom@example.com", phone: "555-0110", relationship: "father", is_primary: true, is_emergency_contact: true },
    medical_notes: "",
    allergies: "None",
    photo_consent: true,
    video_consent: true,
    participation_consent: true,
    coach_notes: "Exceptional talent. Ready for competitive play.",
    status: "active",
    group_id: "group-yellow-1",
    shirt_size: "Youth XL",
    equipment: { racket: true, shoes: true, water_bottle: true },
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2025-05-15T00:00:00Z",
  },
];

export const DEMO_GROUPS: Group[] = [
  { id: "group-red-1", name: "Tiny Stars", age_range: "6-8", stage: "red", default_coach_id: "coach-1", capacity: 8, notes: "Fun-focused, lots of movement games", color: "#ef4444" },
  { id: "group-orange-1", name: "Orange Crushers", age_range: "8-10", stage: "orange", default_coach_id: "coach-1", capacity: 10, notes: "Building rally skills", color: "#f97316" },
  { id: "group-green-1", name: "Green Machine", age_range: "10-12", stage: "green", default_coach_id: "coach-1", capacity: 10, notes: "Point play and strategy", color: "#16a34a" },
  { id: "group-yellow-1", name: "Yellow Jackets", age_range: "12+", stage: "yellow", default_coach_id: "coach-1", capacity: 8, notes: "Match play, full court", color: "#eab308" },
];

const today = new Date().toISOString().split("T")[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split("T")[0];

export const DEMO_SESSIONS: Session[] = [
  { id: "sess-1", title: "Saturday Morning Practice", date: today, time_start: "09:00", time_end: "10:30", location: "Main Court", group_id: "group-orange-1", coach_ids: ["coach-1"], capacity: 10, status: "scheduled", theme: "rally", stage_focus: "orange", notes: "Focus on cooperative rally", equipment_needed: ["cones", "orange balls", "mini nets"], created_at: "2025-05-10T00:00:00Z" },
  { id: "sess-2", title: "Red Ball Fun Hour", date: today, time_start: "10:30", time_end: "11:30", location: "Court 2", group_id: "group-red-1", coach_ids: ["coach-1"], capacity: 8, status: "scheduled", theme: "movement", stage_focus: "red", notes: "Coordination and fun", equipment_needed: ["red balls", "cones", "hoops"], created_at: "2025-05-10T00:00:00Z" },
  { id: "sess-3", title: "Green Group Match Play", date: tomorrow, time_start: "15:00", time_end: "16:30", location: "Main Court", group_id: "group-green-1", coach_ids: ["coach-1"], capacity: 10, status: "scheduled", theme: "match_play", stage_focus: "green", notes: "Scoring and point play", equipment_needed: ["green balls", "score cards"], created_at: "2025-05-10T00:00:00Z" },
];

export const DEMO_ATTENDANCE: AttendanceRecord[] = [
  { id: "att-1", session_id: "sess-1", player_id: "player-1", status: "present", parent_notified: false, checked_in_by: "coach-1", created_at: today + "T09:05:00Z" },
  { id: "att-2", session_id: "sess-1", player_id: "player-6", status: "present", parent_notified: false, checked_in_by: "coach-1", created_at: today + "T09:03:00Z" },
  { id: "att-3", session_id: "sess-2", player_id: "player-3", status: "present", parent_notified: false, checked_in_by: "coach-1", created_at: today + "T10:35:00Z" },
  { id: "att-4", session_id: "sess-2", player_id: "player-7", status: "late", parent_notified: true, notes: "Arrived 10 min late", checked_in_by: "coach-1", created_at: today + "T10:42:00Z" },
];

export const DEMO_ASSESSMENTS: SkillAssessment[] = [
  {
    id: "assess-1",
    player_id: "player-1",
    coach_id: "coach-1",
    date: "2025-05-10",
    overall_stage_recommendation: "orange",
    notes: "Continuing to develop rally skills. Backhand still needs work.",
    items: [
      { id: "si-1", assessment_id: "assess-1", skill_id: "forehand", rating: 3, notes: "Good form, consistent contact", evidence: "practice", recommended_drill: "Partner toss forehand" },
      { id: "si-2", assessment_id: "assess-1", skill_id: "backhand", rating: 2, notes: "Unsure grip, pushes ball", evidence: "observation", recommended_drill: "Backhand target zones" },
      { id: "si-3", assessment_id: "assess-1", skill_id: "rally_ability", rating: 3, notes: "Can sustain 5-6 shot rally", evidence: "drill", recommended_drill: "Bounce-hit rally" },
      { id: "si-4", assessment_id: "assess-1", skill_id: "listening_participation", rating: 5, notes: "Excellent listener, great attitude", evidence: "observation" },
      { id: "si-5", assessment_id: "assess-1", skill_id: "footwork", rating: 3, notes: "Good movement, needs quicker recovery", evidence: "practice", recommended_drill: "Cone island footwork" },
    ],
    created_at: "2025-05-10T00:00:00Z",
  },
];

export const DEMO_PROGRESS_REPORTS: ProgressReport[] = [
  {
    id: "report-1",
    player_id: "player-1",
    title: "May Progress Report",
    period_start: "2025-04-01",
    period_end: "2025-05-31",
    current_stage: "orange",
    attendance_summary: "Attended 8 of 10 sessions (80%)",
    strengths: ["Excellent listener", "Strong forehand development", "Positive attitude"],
    improvements: ["Backhand consistency", "Serve motion"],
    skills_to_practice: ["Backhand target drill", "Serve toss ladder", "Rally challenge"],
    coach_comments: "Emma is a joy to coach. She listens carefully and applies feedback quickly. Her forehand has improved significantly. Focus for next month: backhand and serve.",
    home_activities: ["Wall rally (20 hits)", "Serve toss against wall", "Balance exercises"],
    badges_earned: ["first-rally", "great-listener", "forehand-builder"],
    next_milestone: "Achieve consistent 8-shot rally",
    created_at: "2025-05-15T00:00:00Z",
  },
];

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  { id: "ann-1", title: "Summer Camp Registration Open!", content: "Registration for August tennis camp is now open. Spaces limited.", audience: "all", sent_by: "admin-1", sent_at: "2025-05-15T10:00:00Z", read_count: 12 },
  { id: "ann-2", title: "Saturday Practice Location Change", content: "Saturday practice will be on Court 3 instead of Main Court due to maintenance.", audience: "all", sent_by: "coach-1", sent_at: "2025-05-18T08:00:00Z", read_count: 8 },
  { id: "ann-3", title: "Water Bottle Reminder", content: "Please remind your child to bring a water bottle to every practice. Hydration is important!", audience: "parent", sent_by: "coach-1", sent_at: "2025-05-17T14:00:00Z", read_count: 6 },
];

export const DEMO_PLAYER_BADGES: PlayerBadge[] = [
  { id: "pb-1", player_id: "player-1", badge_id: "first-rally", awarded_by: "coach-1", awarded_at: "2025-04-20T00:00:00Z" },
  { id: "pb-2", player_id: "player-1", badge_id: "great-listener", awarded_by: "coach-1", awarded_at: "2025-04-25T00:00:00Z" },
  { id: "pb-3", player_id: "player-1", badge_id: "forehand-builder", awarded_by: "coach-1", awarded_at: "2025-05-10T00:00:00Z" },
];

export const DEMO_DRILLS: Drill[] = [
  {
    id: "drill-1",
    name: "Cone Island Footwork",
    description: "Players hop between cone stations placed around the court",
    stage: "red",
    duration_minutes: 8,
    equipment: ["cones"],
    min_players: 2,
    max_players: 8,
    category: "movement",
    instructions: ["Place 6 cones in random pattern on mini court", "Player hops to each cone and back", "Add ball toss when ready"],
    coaching_points: ["Stay on toes", "Use small quick steps", "Look forward, not at feet"],
  },
  {
    id: "drill-2",
    name: "Bounce-Hit Rally",
    description: "Cooperative rally counting bounces and hits",
    stage: "orange",
    duration_minutes: 10,
    equipment: ["orange balls", "mini net"],
    min_players: 2,
    max_players: 4,
    category: "rally",
    instructions: ["Player A tosses ball to themselves, hits to partner", "Partner does same", "Count consecutive hits"],
    coaching_points: ["Watch the ball", "Move to contact", "Relaxed grip"],
  },
  {
    id: "drill-3",
    name: "Partner Toss Forehand",
    description: "Partner tosses ball, player hits forehand to target",
    stage: "orange",
    duration_minutes: 8,
    equipment: ["orange balls", "cones"],
    min_players: 2,
    max_players: 6,
    category: "strokes",
    instructions: ["Partner tosses ball underhand", "Player moves to ball, hits forehand", "Aim for cone target"],
    coaching_points: ["Early preparation", "Contact in front", "Follow through to target"],
  },
  {
    id: "drill-4",
    name: "Target Zones",
    description: "Aim for colored zones on the court",
    stage: "green",
    duration_minutes: 10,
    equipment: ["green balls", "flat markers"],
    min_players: 2,
    max_players: 6,
    category: "tactical",
    instructions: ["Place colored zones on court", "Feed balls, player aims for zone", "Score points per target"],
    coaching_points: ["Think before hitting", "Adjust swing path", "Recovery position after shot"],
  },
  {
    id: "drill-5",
    name: "Red-Light Green-Light Footwork",
    description: "Fun reaction game with stopping on cue",
    stage: "red",
    duration_minutes: 5,
    equipment: ["cones"],
    min_players: 3,
    max_players: 10,
    category: "games",
    instructions: ["Players move around cones", "Coach calls 'red' = stop, 'green' = go", "Freeze in ready position"],
    coaching_points: ["Low stance on stop", "Quick reactions", "Balance"],
  },
  {
    id: "drill-6",
    name: "Mini-Net Rally Challenge",
    description: "Cooperative rally over lowered mini net",
    stage: "red",
    duration_minutes: 8,
    equipment: ["red balls", "mini net"],
    min_players: 2,
    max_players: 4,
    category: "rally",
    instructions: ["Lower mini net", "Players rally cooperatively", "Count consecutive hits, beat personal record"],
    coaching_points: ["Soft hands at net", "Controlled swings", "Move to ball early"],
  },
  {
    id: "drill-7",
    name: "Serve Toss Ladder",
    description: "Progressive serve toss accuracy drill",
    stage: "green",
    duration_minutes: 8,
    equipment: ["green balls", "cones", "tape"],
    min_players: 2,
    max_players: 6,
    category: "strokes",
    instructions: ["Mark service boxes with tape", "Player tosses self-fed ball into target", "Progress to full serve"],
    coaching_points: ["Consistent toss", "Ball toss in front", "Body rotates into serve"],
  },
  {
    id: "drill-8",
    name: "Volley Wall",
    description: "Volleys against wall or with partner close to net",
    stage: "green",
    duration_minutes: 8,
    equipment: ["green balls", "wall or net"],
    min_players: 1,
    max_players: 4,
    category: "strokes",
    instructions: ["Stand close to wall/net", "Hit controlled volleys", "Keep ball in play"],
    coaching_points: ["Block, not swing", "Punch volley", "Ready position immediately"],
  },
  {
    id: "drill-9",
    name: "Rally Record Challenge",
    description: "Team cooperative rally counting",
    stage: "green",
    duration_minutes: 10,
    equipment: ["green balls"],
    min_players: 4,
    max_players: 8,
    category: "rally",
    instructions: ["Teams of 2 on court", "Count consecutive hits", "Beat other teams' records"],
    coaching_points: ["Communicate with partner", "Move as a team", "Stay calm under pressure"],
  },
  {
    id: "drill-10",
    name: "Team Sportsmanship Game",
    description: "Match play with sportsmanship scoring",
    stage: "yellow",
    duration_minutes: 15,
    equipment: ["yellow balls", "score cards"],
    min_players: 4,
    max_players: 8,
    category: "games",
    instructions: ["Play mini-matches", "Award bonus points for good sportsmanship", "Rotate opponents frequently"],
    coaching_points: ["Shake hands before and after", "Encourage opponents", "Fair line calls"],
  },
];

export const DEMO_DASHBOARD_STATS: DashboardStats = {
  total_players: 8,
  active_players: 8,
  today_sessions: 2,
  upcoming_sessions: 1,
  attendance_rate: 82,
  players_needing_attention: 2,
  recent_assessments: 5,
  stage_distribution: { red: 2, orange: 2, green: 2, yellow: 2 },
};

const STAGE_FEE: Record<string, number> = { red: 40, orange: 50, green: 60, yellow: 70 };

export const DEMO_PAYMENTS: Record<string, PaymentRecord> = Object.fromEntries(
  DEMO_PLAYERS.map((p, i) => {
    // Mix of paid and unpaid, with varied last-paid dates
    const paid = i % 3 !== 0; // ~2/3 paid
    const lastPaidDate = paid
      ? new Date(Date.now() - (i + 1) * 7 * 86400000).toISOString().split("T")[0]
      : null;
    return [
      p.id,
      { monthlyFee: STAGE_FEE[p.skill_stage] ?? 50, paid, lastPaidDate },
    ];
  })
);

// Simple in-memory store for demo operations
let _players = [...DEMO_PLAYERS];
let _sessions = [...DEMO_SESSIONS];
let _attendance = [...DEMO_ATTENDANCE];
let _assessments = [...DEMO_ASSESSMENTS];
let _progressReports = [...DEMO_PROGRESS_REPORTS];
let _announcements = [...DEMO_ANNOUNCEMENTS];
let _playerBadges = [...DEMO_PLAYER_BADGES];
let _groups = [...DEMO_GROUPS];

export const mockStore = {
  get players() { return _players; },
  set players(v) { _players = v; },
  get sessions() { return _sessions; },
  set sessions(v) { _sessions = v; },
  get attendance() { return _attendance; },
  set attendance(v) { _attendance = v; },
  get assessments() { return _assessments; },
  set assessments(v) { _assessments = v; },
  get progressReports() { return _progressReports; },
  set progressReports(v) { _progressReports = v; },
  get announcements() { return _announcements; },
  set announcements(v) { _announcements = v; },
  get playerBadges() { return _playerBadges; },
  set playerBadges(v) { _playerBadges = v; },
  get groups() { return _groups; },
  set groups(v) { _groups = v; },
};
